import { Type } from 'class-transformer';
import { IsInt, IsOptional, IsString, Max, Min } from 'class-validator';
import { ApiPropertyOptional } from '@nestjs/swagger';

/** Page size used when the client does not supply `limit`. */
export const DEFAULT_PAGE_SIZE = 20;

/** Hard ceiling on page size, regardless of what the client asks for. */
export const MAX_PAGE_SIZE = 100;

/**
 * A real cursor, shown in the docs. Generated by `encodeCursor`, not written by
 * hand — a token that does not round-trip would send readers straight into a
 * 400. Asserted in cursor-pagination-query.dto.spec.ts.
 */
export const EXAMPLE_CURSOR =
  'eyJwIjoxLCJ2IjpbIjIwMjYtMDctMjBUMTA6MDM6MDAuMDAwWiJdLCJpIjoiYTE1ZjhkNjItM2U3Yy00YjA5LThmMjQtNmMxYjlhMGQzZTc1IiwicyI6IjBlZGJlNDg4ODI0ZCJ9';

/**
 * Shared query params for every cursor-paginated list endpoint.
 *
 * Endpoints that never had offset params (e.g. GET /v1/solutions) extend this
 * directly. Endpoints migrating away from offset pagination extend
 * {@link DeprecatedOffsetPaginationQueryDto} instead, which keeps the legacy
 * params accepted so existing clients do not break.
 */
export class CursorPaginationQueryDto {
  @ApiPropertyOptional({
    description:
      'Opaque cursor from a previous response `nextCursor`. Omit to fetch the first page.',
    example: EXAMPLE_CURSOR,
  })
  @IsOptional()
  @IsString()
  cursor?: string;

  @ApiPropertyOptional({
    description: `Number of items to return. Max ${MAX_PAGE_SIZE}.`,
    minimum: 1,
    maximum: MAX_PAGE_SIZE,
    default: DEFAULT_PAGE_SIZE,
  })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  @Max(MAX_PAGE_SIZE)
  limit?: number = DEFAULT_PAGE_SIZE;

  @ApiPropertyOptional({
    description: 'Whether to include soft-deleted records (e.g. for moderation/audit review)',
    default: false,
  })
  @IsOptional()
  @Type(() => Boolean)
  includeDeleted?: boolean = false;
}

/**
 * Cursor pagination plus the legacy offset params, retained purely for
 * backwards compatibility on endpoints that previously exposed them.
 *
 * `page` is accepted and validated but has **no effect** — these endpoints are
 * cursor-only. It exists because the global ValidationPipe runs with
 * `forbidNonWhitelisted: true`, so removing the property outright would turn
 * every existing `?page=` request into a 400 instead of a soft deprecation.
 *
 * @deprecated Remove `page` once the deprecation window in the API changelog
 * has elapsed.
 */
export class DeprecatedOffsetPaginationQueryDto extends CursorPaginationQueryDto {
  @ApiPropertyOptional({
    deprecated: true,
    description:
      'DEPRECATED — offset pagination has been replaced by cursor pagination. ' +
      'This param is accepted for backwards compatibility but is ignored. ' +
      'Use `cursor` instead. See the API changelog for the migration note.',
  })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  page?: number;
}
